# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://jeffshomali.github.io/
baseurl:
title: Jeff Shomali Personal Blog
author: Jeff Shomali
description: Personal blog and resume
avatar: profile.png
email: info@jeffshomali.com
github: JeffShomali # username
twitter: jeffshomali
linkedin: jeffShomali
stackoverflow: username   #e.g: users/2735833/proton1h1
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-41121717-2


# needed for travis-ci build
exclude: [vendor]
